//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPSoftworks.DevNumbers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPSoftworks.DevNumbers.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0}.
        /// </summary>
        internal static string Command_CopyValue0_Title {
            get {
                return ResourceManager.GetString("Command_CopyValue0_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show conversions of {0}....
        /// </summary>
        internal static string ConversionFallbackSubtitle {
            get {
                return ResourceManager.GetString("ConversionFallbackSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the query.
        /// </summary>
        internal static string ErrorInQuery {
            get {
                return ResourceManager.GetString("ErrorInQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to binary.
        /// </summary>
        internal static string NumberBase_Binary {
            get {
                return ResourceManager.GetString("NumberBase_Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character.
        /// </summary>
        internal static string NumberBase_Character {
            get {
                return ResourceManager.GetString("NumberBase_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimal.
        /// </summary>
        internal static string NumberBase_DecimalLabel {
            get {
                return ResourceManager.GetString("NumberBase_DecimalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimal (signed).
        /// </summary>
        internal static string NumberBase_DecimalSigned {
            get {
                return ResourceManager.GetString("NumberBase_DecimalSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimal (unsigned).
        /// </summary>
        internal static string NumberBase_DecimalUnsigned {
            get {
                return ResourceManager.GetString("NumberBase_DecimalUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hexadecimal.
        /// </summary>
        internal static string NumberBase_Hexadecimal {
            get {
                return ResourceManager.GetString("NumberBase_Hexadecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to octal.
        /// </summary>
        internal static string NumberBase_Octal {
            get {
                return ResourceManager.GetString("NumberBase_Octal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a number to convert (123, 0xFF, 234hex, 0b1011_0110, 0&apos;123&apos;456).
        /// </summary>
        internal static string NumberBaseConversionPage_Placeholder {
            get {
                return ResourceManager.GetString("NumberBaseConversionPage_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze and convert numbers to hex, binary, ASCII, and more.
        /// </summary>
        internal static string NumberBaseConversionPage_Subtitle {
            get {
                return ResourceManager.GetString("NumberBaseConversionPage_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Numbers.
        /// </summary>
        internal static string NumberBaseConversionPage_Title {
            get {
                return ResourceManager.GetString("NumberBaseConversionPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of bounds.
        /// </summary>
        internal static string OutOfBounds {
            get {
                return ResourceManager.GetString("OutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Numbers.
        /// </summary>
        internal static string Product_Title {
            get {
                return ResourceManager.GetString("Product_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze and convert numbers to hex, binary, ASCII, and more.
        /// </summary>
        internal static string ProgrammerNumbers_Subtitle {
            get {
                return ResourceManager.GetString("ProgrammerNumbers_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Numbers.
        /// </summary>
        internal static string ProgrammerNumbers_Title {
            get {
                return ResourceManager.GetString("ProgrammerNumbers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean {0} input as binary?.
        /// </summary>
        internal static string QueryItem_DidYouMean0AsBinary {
            get {
                return ResourceManager.GetString("QueryItem_DidYouMean0AsBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to display numbers after conversion.
        /// </summary>
        internal static string Setting_DefaultFormattingStyle_Subtitle {
            get {
                return ResourceManager.GetString("Setting_DefaultFormattingStyle_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default style.
        /// </summary>
        internal static string Setting_DefaultFormattingStyle_Title {
            get {
                return ResourceManager.GetString("Setting_DefaultFormattingStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ada style (16#FF#, 2#1010#).
        /// </summary>
        internal static string StyleName_AdaStyle {
            get {
                return ResourceManager.GetString("StyleName_AdaStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ style (with &apos; as digit group separator).
        /// </summary>
        internal static string StyleName_CppStyle {
            get {
                return ResourceManager.GetString("StyleName_CppStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# style (with _ as digit group separator).
        /// </summary>
        internal static string StyleName_CSharp {
            get {
                return ResourceManager.GetString("StyleName_CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (infer from input).
        /// </summary>
        internal static string StyleName_Infer {
            get {
                return ResourceManager.GetString("StyleName_Infer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multicharacter suffix (FFhex, 123dec, 111bin).
        /// </summary>
        internal static string StyleName_MultiCharSuffix {
            get {
                return ResourceManager.GetString("StyleName_MultiCharSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISP style (16rFF, 2r1010).
        /// </summary>
        internal static string StyleName_RStyle {
            get {
                return ResourceManager.GetString("StyleName_RStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single character prefix (hFF).
        /// </summary>
        internal static string StyleName_SingleCharPrefix {
            get {
                return ResourceManager.GetString("StyleName_SingleCharPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single character suffix (FFh, 17o).
        /// </summary>
        internal static string StyleName_SingleCharSuffix {
            get {
                return ResourceManager.GetString("StyleName_SingleCharSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special character prefix (#FF, @77, %11).
        /// </summary>
        internal static string StyleName_SpecialCharPrefix {
            get {
                return ResourceManager.GetString("StyleName_SpecialCharPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard style.
        /// </summary>
        internal static string StyleName_Standard {
            get {
                return ResourceManager.GetString("StyleName_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB style (&amp;hFF, &amp;b1010, &amp;o777).
        /// </summary>
        internal static string StyleName_VBStyle {
            get {
                return ResourceManager.GetString("StyleName_VBStyle", resourceCulture);
            }
        }
    }
}
